services:
  _defaults:
    autowire: true
    autoconfigure: true

  MirandaLeyva\ContaoCourseManagementBundle\Controller\:
    resource: "../src/Controller/"

  MirandaLeyva\ContaoCourseManagementBundle\Model\:
    resource: "../src/Model/"
