services:
  _defaults:
    autowire: true
    autoconfigure: true

  MirandaLeyva\ContaoCourseManagementBundle\Controller\:
    resource: "../../Controller/"

  MirandaLeyva\ContaoCourseManagementBundle\Model\:
    resource: "../../Model/"

  MirandaLeyva\ContaoCourseManagementBundle\Service\:
    resource: "../../Service/"
